In [2]:
import pandas as pd

In [3]:
#Read CSV
df = pd.read_csv("data.csv")

In [4]:
df

   Name School  Marks
0  Abhi   JSPM     69

In [6]:
df1 = pd.read_csv("Newdata.csv", usecols=["Actor", "Film", "Year"], nrows=10)

# Write CSV

In [9]:
df1.to_csv("output.csv", index=False)

In [10]:
# Read Excel

In [32]:
df = pd.read_excel("file1.xlsx")
df

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [ ]:
# pd.read_excel("data.xlsx", sheet_name="Sales")

In [35]:
#Write Excel
df.to_excel("output.xlsx", index=False)

Multiple sheets:

with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)

In [36]:
df = pd.read_json("data.json")
df

    name    lang
0  harry  python
1    jay    java

In [28]:
# import os

#os.listdir()

In [29]:
# pip install xlrd